import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import ReactQueryProvider from "./providers/ReactQueryProvider";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Web Book - React Take Home Test',
  description: 'Generated by create next app',
};

export default function RootLayout({children}:{children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  )
}
